<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
      <Description>An adaptor to allow EasyNetQ to use System.Text.Json serializer</Description>
      <TargetFrameworks>net9.0</TargetFrameworks>
      <Nullable>enable</Nullable>
      <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>
    <ItemGroup>
      <ProjectReference Include="..\EasyNetQ\EasyNetQ.csproj" />
    </ItemGroup>
</Project>
